name: CraftAnti
main: com.craftvn.craftanti.CraftAnti
version: 1.0.0
api-version: '1.20'
author: CraftVN
website: https://craftvn.net
commands:
  craftanti:
    description: CraftAnti admin command
    usage: /craftanti <reload|info>
    permission: craftanti.admin
permissions:
  craftanti.admin:
    default: op
  craftanti.alert:
    default: op
  craftanti.bypass:
    default: op
